### ISSUE TITLE
Proposition to change content location from root route to something specific 

### ISSUE THREAD

**Issue by parth-07** [manorit2001/MediaServer#8]
**Proposition to change content location from root route to something specific to avoid polluting global routes namespace**

All content location (media and directories list view) should start from some specific base route, for example _/content_ . 
This will be beneficial in the following ways .

- As the app grows , there may be need for different pages and get requests to be served . Wildchar route to all get requests as we are currently using will cause issues and extra overheads in building and maintaing code  those pages and routes.

- Since main purpose of the app is ease of use , and directory listing in root route provide significant ease , we can redirect all get requests to root route to _/content_ route which will serve all media contents and directory list view . Thus users will only need to open website root only , just like before . Thus there should not be much overhead to make the change .

**Comment by manorit2001** [comment]
it's a good suggestion, we will do it if we will scale this app to incorporate more pages in the client side
